### ISSUE TITLE
Travis build needs to deploy dist/ folder to npmjs

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/tasks-scheduler#5]
The library produces a bablified version of the library to use it in the browser (`npm install` creates the `dist/` folder). The version deployed to npmjs.org doesn't contain the `dist` folder but only the `src` folder, which means it's not usable from the browser.

**Comment by ankon** [comment]
I'm not 100% sure, but it right now we're only distributing the `lib/` and `dist/` directories. It might make sense to also include `src/`, but then again the babelized output right now looks good enough for debugging. Having `src/` available could make contributions easier though -- but then we should also produce proper source maps.
